- name: Gathering Arista Device Facts
  hosts: localhost
  gather_facts: no
  vars_files:
    - rtr2-creds.yml
  tasks:
    - name: Gather Arista info using API
      ansible.builtin.uri:
        url: "http://{{ device_ip }}/command-api"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "runCmds"
          params:
            version: "latest"
            cmds: 
              - "show version"
            format: "json"
            timestamps: "false"
          id: "1"
        user: "{{ device_username }}"
        password: "{{ device_password }}"
        status_code: 200
      register: arista_info
    - name: set fact for device
      set_fact:
        cacheable: true
        arista_version: "{{ arista_info.json.result[0].version }}"
      delegate_to: "{{ device_ip }}"
      delegate_facts: true
      